// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnoiJgzd2i7AjwWtL9mrb_BavpswrTy4c',
    appId: '1:201404011086:web:df6c5f4742feff9573e91f',
    messagingSenderId: '201404011086',
    projectId: 'oc-notes',
    authDomain: 'oc-notes.firebaseapp.com',
    storageBucket: 'oc-notes.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTI2aap5hOSyKziG66D0NTfdWNc5_e47Y',
    appId: '1:201404011086:android:792f31951d89b4bc73e91f',
    messagingSenderId: '201404011086',
    projectId: 'oc-notes',
    storageBucket: 'oc-notes.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHjJ195NbvPNlIwRId70DH_BwNZTF6eTE',
    appId: '1:201404011086:ios:619f3a8e0158359373e91f',
    messagingSenderId: '201404011086',
    projectId: 'oc-notes',
    storageBucket: 'oc-notes.firebasestorage.app',
    iosBundleId: 'com.example.privatenotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHjJ195NbvPNlIwRId70DH_BwNZTF6eTE',
    appId: '1:201404011086:ios:619f3a8e0158359373e91f',
    messagingSenderId: '201404011086',
    projectId: 'oc-notes',
    storageBucket: 'oc-notes.firebasestorage.app',
    iosBundleId: 'com.example.privatenotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnoiJgzd2i7AjwWtL9mrb_BavpswrTy4c',
    appId: '1:201404011086:web:7ab7bb7719fa406473e91f',
    messagingSenderId: '201404011086',
    projectId: 'oc-notes',
    authDomain: 'oc-notes.firebaseapp.com',
    storageBucket: 'oc-notes.firebasestorage.app',
  );
}
